// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttvuqgcgknkicggsnlke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0dnVxZ2Nna25raWNnZ3NubGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTI5NTYsImV4cCI6MjA2MTQ4ODk1Nn0.TWgcKYAj9GdafkZz06U_VunyyCck5P5yV7r4UL5i5po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);